[#5] copy original string in string replace
istana/libnss-maria pull request #12
Opened 2020-12-04 17:20 UTC by istana

2020-12-04 19:08 UTC, xHire requested changes

2020-12-04 19:08 UTC, xHire commented on src/str_replace.c
> +    strcpy(orig_copy, orig);
Since you’re changing this to avoid a race condition, `strncpy` with the limit of allocated memory would be more suitable here.

2020-12-04 19:08 UTC, xHire commented on src/str_replace.c
>          return NULL;
You leak the memory of `orig_copy` here.

2020-12-04 19:08 UTC, xHire commented on src/str_replace.c
> +        return NULL;
Here you leak also the memory of `result`.

2021-01-11 05:48 UTC, istana commented
Fails because of docker rate limits. Will move from Travis to GH Actions later

2021-01-11 05:49 UTC, merged